name: SSH Service
on: push

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: lscr.io/linuxserver/openssh-server:latest
        # Provide the password for postgres
        env:
          SUDO_ACCESS: false
          PASSWORD_ACCESS: true
          USER_PASSWORD: password
          USER_NAME: linuxserver.io
        ports:
          # Maps tcp port 5432 on service container to the host
          - 2222:2222

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print SSH Connection Details
        id: ssh
        run: |
          echo "SSH Server is running."
          echo "You can connect using the following command:"
          echo "ssh root@$(curl -s ifconfig.me) -p 22"
          echo CURRENT_IP=$(curl -s ifconfig.me) >> $GITHUB_OUTPUT

      - name: executing remote ssh commands using password (0.1.3)
        uses: appleboy/ssh-action@v0.1.3
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: linuxserver.io
          password: password
          port: 2222
          script: whoami

      - name: executing remote ssh commands using password (0.1.4)
        uses: appleboy/ssh-action@v0.1.4
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: linuxserver.io
          password: password
          port: 2222
          script: whoami

      - name: executing remote ssh commands using password (0.1.5)
        uses: appleboy/ssh-action@v0.1.5
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: linuxserver.io
          password: password
          port: 2222
          script: whoami

      - name: executing remote ssh commands using password (1.0.3)
        uses: appleboy/ssh-action@v1.0.3
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: linuxserver.io
          password: password
          port: 2222
          script: whoami
