name: Setup SSH Server

on: [push]

jobs:
  setup-ssh-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Server
        run: sudo apt-get update && sudo apt-get install -y openssh-server

      - name: Configure SSH Server
        run: |
          sudo mkdir -p /var/run/sshd
          echo 'root:password' | sudo chpasswd
          sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh start

      - name: Display SSH Server Status
        run: sudo service ssh status

      - name: Print SSH Connection Details
        id: ssh
        run: |
          echo "SSH Server is running."
          echo "You can connect using the following command:"
          echo "ssh root@$(curl -s ifconfig.me) -p 22"
          echo CURRENT_IP=$(curl -s ifconfig.me) >> $GITHUB_OUTPUT
          ssh root@$(curl -s ifconfig.me) -p 22

      - name: executing remote ssh commands using password (0.1.3)
        uses: appleboy/ssh-action@v0.1.3
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: root
          password: password
          port: 22
          script: whoami

      - name: executing remote ssh commands using password (0.1.4)
        uses: appleboy/ssh-action@v0.1.4
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: root
          password: password
          port: 22
          script: whoami

      - name: executing remote ssh commands using password (0.1.5)
        uses: appleboy/ssh-action@v0.1.5
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: root
          password: password
          port: 22
          script: whoami

      - name: executing remote ssh commands using password (1.0.3)
        uses: appleboy/ssh-action@v1.0.3
        if: always()
        with:
          host: ${{ steps.ssh.outputs.CURRENT_IP }}
          username: root
          password: password
          port: 22
          script: whoami
